import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/context/AuthContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-[100vh] max-h-screen relative">
        <AuthProvider>        
          {children}
          <Navbar />
        </AuthProvider>
      </body>
    </html>
  );
}
