export const palabras = [
    "abeja", "barco", "casa", "dado", "elefante", "flor", "gato", "hoja", "isla", "jirafa", 
    "kilo", "luna", "manzana", "nube", "oso", "pato", "queso", "ratón", "sol", "tigre", 
    "uva", "vaca", "wafle", "xilófono", "yate", "zorro", "auto", "bicicleta", "camión", 
    "diamante", "espejo", "faro", "globo", "hacha", "iguana", "jardín", "koala", "limón", 
    "mesa", "naranja", "ojo", "pelota", "quiosco", "reloj", "silla", "teléfono", "uña", 
    "ventana", "web", "xenón", "yogur", "zapato", "agua", "bebida", "carro", "delfín", 
    "escalera", "fuego", "guitarra", "huevo", "iglesia", "jabón", "kilómetro", "lápiz", 
    "montaña", "nido", "océano", "puente", "quesadilla", "rosa", "sombrero", "tren", 
    "uniforme", "verde", "wind", "xilo", "yegua", "zoológico", "aeropuerto", "balcón", 
    "cuchara", "dinosaurio", "escuela", "fútbol", "guitarra", "helado", "imán", "juego", 
    "kilovatio", "libro", "manta", "nieve", "órgano", "patio", "química", "resorte", 
    "sombrilla", "teatro", "universidad", "vino", "waterpolo", "xilografía", "yerba", 
    "zanahoria", "almohada", "banco", "ciruela", "dólar", "elección", "fruta", "galleta", 
    "hielo", "internet", "jabonera", "kárate", "lámpara", "mariposa", "niño", "orquesta", 
    "parque", "quinto", "ratonera", "sombra", "tambor", "uruguay", "valle", "watt", 
    "xenón", "yema", "zócalo", "árbol", "bicicleta", "ciudad", "diario", "estrella", 
    "foto", "granada", "hipopótamo", "invierno", "jirafa", "karate", "lago", "mamá", 
    "noche", "oro", "país", "queso", "radio", "sal", "tigre", "uva", "vaso", "wafle", 
    "xilófono", "yate", "zebra", "aire", "baño", "cocina", "dinero", "elefante", 
    "fiesta", "guitarra", "hotel", "invierno", "juego", "kilo", "limón", "mujer", 
    "nieve", "ola", "piedra", "queso", "reloj", "sol", "tren", "uva", "viento", "wifi", 
    "xilografía", "yogur", "zumo", "abanico", "burro", "coche", "diente", "espejo", 
    "foco", "guitarra", "hilo", "inodoro", "jugo", "koala", "león", "montaña", "nube", 
    "ojo", "perro", "quesadilla", "río", "silla", "teléfono", "uvas", "violín", "waffle", 
    "xilófono", "yoyo", "zapato", "acantilado", "bote", "ciudad", "dedal", "esfera", 
    "flauta", "gato", "hombre", "iglesia", "jardín", "kilo", "libro", "mesa", "nube", 
    "ojal", "pared", "queso", "rosal", "sombrero", "túnel", "ultrasonido", "vaca", 
    "watt", "xilófono", "yegua", "zafiro", "aurora", "barco", "colina", "dinero", 
    "elefante", "faro", "golfo", "héroe", "iglesia", "juego", "kilómetro", "lámpara", 
    "montaña", "noche", "oruga", "puente", "queso", "reloj", "sombra", "tren", 
    "uva", "vino", "wincha", "xilófono", "yogur", "zorra", "aeropuerto", "burbuja", 
    "cocina", "dormitorio", "espejo", "flor", "globo", "helicóptero", "iglesia", 
    "jardín", "kilovatio", "lámpara", "montaña", "nieve", "orilla", "piscina", 
    "queso", "río", "sol", "tren", "uña", "valle", "wifi", "xilófono", "yogur", 
    "zapato", "anillo", "batería", "cuchillo", "dibujo", "espejo", "faro", "globo", 
    "huevo", "imán", "jabón", "kilovatio", "lago", "manta", "nieve", "oreja", "pared", 
    "queso", "río", "sombrero", "tren", "uva", "ventana", "watt", "xilófono", "yate", 
    "zebra", "árbol", "burro", "cabeza", "dormir", "estrella", "fuego", "guante", 
    "herradura", "isla", "jirafa", "kilovatio", "luz", "manzana", "nieve", "océano", 
    "pelota", "queso", "río", "sombrilla", "tren", "uvas", "vino", "waffle", "xilófono", 
    "yogur", "zorro", "almohada", "burro", "canguro", "dinero", "estrella", "fuego", 
    "globo", "herramienta", "iglesia", "jirafa", "kilómetro", "luz", "manta", "nieve", 
    "océano", "pelota", "queso", "río", "sombrero", "tren", "uva", "valle", "wifi", 
    "xilófono", "yate", "zanahoria", "alba", "buzo", "ciudad", "dinero", "espejo", 
    "flor", "globo", "herramienta", "iglesia", "jabón", "kilómetro", "limón", "manta", 
    "nieve", "océano", "piscina", "queso", "río", "sombrero", "tren", "uvas", "viento", 
    "watt", "xilófono", "yogur", "zapato", "aire", "burro", "cabeza", "dibujo", 
    "estrella", "faro", "globo", "herramienta", "iglesia", "jabón", "kilómetro", 
    "limón", "manta", "nieve", "océano", "piscina", "queso", "río", "sombrero", 
    "tren", "uva", "valle", "watt", "xilófono", "yate", "zorra", "abeja", "banco", 
    "cuchara", "delfín", "estrella", "fuego", "globo", "herramienta", "iglesia", 
    "jabón", "kilómetro", "limón", "manta", "nieve", "océano", "piscina", "queso", 
    "río", "sombrero", "tren", "uvas", "valle", "watt", "xilófono", "yogur", 
    "zorro", "abeja", "barco", "cuchara", "delfín", "estrella", "fuego", "globo", 
    "herramienta", "iglesia", "jabón", "kilómetro", "limón", "manta", "nieve", 
    "océano", "piscina", "queso", "río", "sombrero", "tren", "uvas", "valle", 
    "watt", "xilófono", "yogur", "zapato", "abeja", "barco", "cuchara", "delfín", 
    "estrella", "fuego", "globo", "herramienta", "iglesia", "jabón", "kilómetro", 
    "limón", "manta", "nieve", "océano", "piscina", "queso", "río", "sombrero", 
    "tren", "uvas", "valle", "watt", "xilófono", "yogur", "zapato", "abeja", 
    "barco", "cuchara", "delfín", "estrella", "fuego", "globo", "herramienta", 
    "iglesia", "jabón", "kilómetro", "limón", "manta", "nieve", "océano", 
    "piscina", "queso", "río", "sombrero", "tren", "uvas", "valle", "watt", 
    "xilófono", "yogur", "zapato", "abeja", "barco", "cuchara", "delfín", 
    "estrella", "fuego", "globo", "herramienta", "iglesia", "jabón", "kilómetro", 
    "limón", "manta", "nieve", "océano", "piscina", "queso", "río", "sombrero", 
    "tren", "uvas", "valle", "watt", "xilófono", "yogur", "zapato", "abeja", 
    "barco", "cuchara", "delfín", "estrella", "fuego", "globo", "herramienta", 
    "iglesia", "jabón", "kilómetro", "limón", "manta", "nieve", "océano", 
    "piscina", "queso", "río", "sombrero", "tren", "uvas", "valle", "watt", 
    "xilófono", "yogur", "zapato", "abeja", "barco", "cuchara", "delfín", 
    "estrella", "fuego", "globo", "herramienta", "iglesia", "jabón", "kilómetro", 
    "limón", "manta", "nieve", "océano", "piscina", "queso", "río", "sombrero", 
    "tren", "uvas", "valle", "watt", "xilófono", "yogur", "zapato", "abeja", 
    "barco", "cuchara", "delfín", "estrella", "fuego", "globo", "herramienta", 
    "iglesia", "jabón", "kilómetro", "limón", "manta", "nieve", "océano", 
    "piscina", "queso", "río", "sombrero", "tren", "uvas", "valle", "watt", 
    "xilófono", "yogur", "zapato"
  ];
  